### ISSUE TITLE
Port 5000 is already in use, cannot start Sandbox

### ISSUE THREAD

**Issue by jwilleke** [activescott/web-app-stack#56]
Un-able to build

``` bash
(base) % npm run install-all

> @activescott/web-app-stack@1.0.0 install-all
> npm run install-server; npm run install-client;


> @activescott/web-app-stack@1.0.0 install-server
> pushd .; cd server; npm install; popd

/Volumes/ESSD1/GitHub/web-app-stack /Volumes/ESSD1/GitHub/web-app-stack

added 1049 packages, and audited 1484 packages in 14s

33 vulnerabilities (19 moderate, 14 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
/Volumes/ESSD1/GitHub/web-app-stack

> @activescott/web-app-stack@1.0.0 install-client
> pushd .; cd client; npm install; popd

/Volumes/ESSD1/GitHub/web-app-stack /Volumes/ESSD1/GitHub/web-app-stack

added 2728 packages, and audited 3163 packages in 32s

1 package is looking for funding
  run `npm fund` for details

174 vulnerabilities (140 moderate, 33 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
/Volumes/ESSD1/GitHub/web-app-stack
(base) jim@jmac web-app-stack % npm start

> @activescott/web-app-stack@1.0.0 start
> pushd .; cd server; npm run start; popd

/Volumes/ESSD1/GitHub/web-app-stack /Volumes/ESSD1/GitHub/web-app-stack

> @activescott/web-app-stack-server@1.0.0 start
> npm run build-testing && ./node_modules/.bin/arc sandbox


> @activescott/web-app-stack-server@1.0.0 build-testing /Volumes/ESSD1/GitHub/web-app-stack/server
> npm run -s build-production

/Volumes/ESSD1/GitHub/web-app-stack/server /Volumes/ESSD1/GitHub/web-app-stack/server
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Compiled successfully.

File sizes after gzip:

  119.85 KB  build/static/js/2.34824f19.chunk.js
  24.48 KB   build/static/css/2.54b324f0.chunk.css
  5.11 KB    build/static/js/main.31d5a150.chunk.js
  793 B      build/static/js/runtime-main.77ead0a2.js
  689 B      build/static/css/main.81ff020b.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

/Volumes/ESSD1/GitHub/web-app-stack/server
         App ⌁ webappstack
      Region ⌁ us-west-2
     Profile ⌁ @aws profile / AWS_PROFILE not configured
     Version ⌁ Architect 8.4.5
         cwd ⌁ /Volumes/ESSD1/GitHub/web-app-stack/server

⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with shared: src/shared
✓ Hydrate Finished checks, nothing to hydrate
         App ⌁ webappstack
      Region ⌁ us-west-2
     Profile ⌁ @aws profile / AWS_PROFILE not configured
     Version ⌁ Architect 8.4.5
         cwd ⌁ /Volumes/ESSD1/GitHub/web-app-stack/server

✓ Sandbox Found Architect project manifest: app.arc
✓ Sandbox No testing environment variables found
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with shared: src/shared
✓ Sandbox Project files hydrated into functions
/Volumes/ESSD1/GitHub/web-app-stack/server/node_modules/@architect/sandbox/src/lib/ports.js:56
    throw err
    ^

Error: Port 5000 is already in use, cannot start Sandbox
    at Server.<anonymous> (/Volumes/ESSD1/GitHub/web-app-stack/server/node_modules/@architect/sandbox/src/lib/ports.js:54:13)
    at Object.onceWrapper (events.js:421:26)
    at Server.emit (events.js:314:20)
    at Server.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (net.js:1344:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

Did find this reference: <https://github.com/architect/sandbox/pull/629>

**Comment by activescott** [comment]
This is because port 5000 isn’t open and the sandbox uses it by default. You can change the port at https://github.com/activescott/web-app-stack/blob/b0be9d5b0ceac218235489f5258e74ebb3546ea5/server/package.json#L16
There is a —ports flag as documented at https://arc.codes/docs/en/reference/cli/sandbox

But will probably have to change it somewhere else too as I cannot remember all what will connect to it off hand. DynamoDB connection?

**Comment by activescott** [comment]
I’d just try —ports and go from there. Hopefully Architect will figure the ports out. If not post an error here and I’ll look closer when I have a minute today/tonight

**Comment by jwilleke** [comment]
Who would have thought. Appears on Monterey (and later macos) Control Center use 5000 and 7000.
Airplay apparently launches as the user on these ports by default.
